[build-system]
requires = ["setuptools >= 38.3.0", "wheel", "versioneer-518"]
build-backend = "setuptools.build_meta"

[tool.codespell]
skip = '.git,*.pdf,*.svg,versioneer.py'
#
# ignore-words-list = ''
